/*
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.ui;

import com.google.inject.Injector;
import org.architecture.cnl.ui.internal.CnlActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ArchcnlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CnlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CnlActivator activator = CnlActivator.getInstance();
		return activator != null ? activator.getInjector(CnlActivator.ORG_ARCHITECTURE_CNL_ARCHCNL) : null;
	}

}
