/*
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ArchcnlUiModule extends AbstractArchcnlUiModule {

	public ArchcnlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
